apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kamichain-data
  namespace: kamichain-demo
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
